### ISSUE TITLE
zshrc not getting sourced? I'm guessing I'm missing a step

### ISSUE THREAD

**Issue by sdellysse** [viperML/noshell#7]
Hi there,

I have added noshell to my `/etc/nixos/flake.nix` file, and in `/etc/passwd` I see that my login user has `/run/current-system/sw/bin/noshell` as it's shell. In my home manager config, I have the following:

```nix
      programs.zsh = { enable = true; };
      xdg.configFile."shell".source = "${pkgs.zsh}/bin/zsh";
```

When I open `Konsole` with this setup (after rebooting), my `~/.zshrc` isn't sourced, and to be honest I'm not entirely sure if `zsh` is getting invoked at all. When I run `zsh` from that command line, it then shows my prompt and everything, screenshots below:

![image](https://github.com/viperML/noshell/assets/293035/18983882-cd2c-4e8a-83fb-6c308900c888)

I'm guessing I'm missing a step or something?

**Comment by viperML** [comment]
probably #4

**Comment by sdellysse** [comment]
yup, that's it. for now, I did this, and I think it works

```nix
xdg.configFile."shell" = {
  executable = true;
  text = ''
    #!${pkgs.zsh}/bin/zsh

    if [[ -o interactive ]] ; then
      if [[ -o login ]] ; then
        exec ${pkgs.zsh}/bin/zsh --interactive --login "$@"
      fi

      exec ${pkgs.zsh}/bin/zhs --interactive "$@"
    fi

    if [[ -o login ]] ; then
      exec ${pkgs.zsh}/bin/zsh --login "$@"
    fi

    exec ${pkgs.zsh}/bin/zsh "$@"
  '';
```

this gives me this output:

![image](https://github.com/viperML/noshell/assets/293035/3702a18a-627a-47ce-9635-2b1c05394af5)

**Comment by gekoke** [comment]
Is there a better way to do this than @sdellysse's script? Both `xdg.configFile."shell".source = "${pkgs.zsh}/bin/zsh";` and the current example in the `README.md` fail to get zsh running for me.

**Comment by viperML** [comment]
I thought this was fixed in that PR from last year, could you give me the steps to reproduce your issue?

**Comment by gekoke** [comment]
Sure, try `nix run github:gekoke/noshell-repro#nixosConfigurations.default.config.system.build.vmWithBootLoader`

Login with `test` and `password`. You should see a plain `$` prompt.

`nix run github:gekoke/noshell-repro#nixosConfigurations.expected.config.system.build.vmWithBootLoader` for the expected behavior.

Writing this test case made me realize that it might be the `programs.zsh.enable = true` [NixOS module option that does a lot of the heavy lifting](https://github.com/NixOS/nixpkgs/blob/5ae3b07d8d6527c42f17c876e404993199144b6a/nixos/modules/programs/zsh/zsh.nix#L25C1-L26C78). This is one of the options I disabled when using noshell. But even with that enabled (`nix run github:gekoke/noshell-repro#nixosConfigurations.maybefix.config.system.build.vmWithBootLoader`), it doesn't seem to work.

**Comment by Rutherther** [comment]
What happens if you run `zsh` inside that prompt, does it start zsh in the way you would expect?
Also, can you send output of `ps f -g$$` when you open the shell?

**Comment by gekoke** [comment]
> What happens if you run `zsh` inside that prompt, does it start zsh in the way you would expect?

Yes.

> Also, can you send output of `ps f -g$$` when you open the shell?

Will test tomorrow

**Comment by gekoke** [comment]
So looking at #4 and #8, I think the issue is that home-manager links the file `shell` to a file in the Nix store with the same name (i.e. `shell`) when using the `source` argument:

```sh
geko in ~/.config 
❯ exa -l        
# Output redacted
lrwxrwxrwx - geko 27 Nov 10:50 shell -> /nix/store/4i14b6xm10kapc6rmjpi94r4hxyfbqrl-home-manager-files/.config/shell
lrwxrwxrwx - geko 27 Nov 10:50 starship.toml -> /nix/store/4i14b6xm10kapc6rmjpi94r4hxyfbqrl-home-manager-files/.config/starship.toml
lrwxrwxrwx - geko 27 Nov 10:50 user-dirs.conf -> /nix/store/4i14b6xm10kapc6rmjpi94r4hxyfbqrl-home-manager-files/.config/user-dirs.conf
lrwxrwxrwx - geko 27 Nov 10:50 user-dirs.dirs -> /nix/store/4i14b6xm10kapc6rmjpi94r4hxyfbqrl-home-manager-files/.config/user-dirs.dirs
```

So when zsh looks at its argv, it goes into the shell compatibility mode or whatever, as described in #4 

I just made an extra link to force the filename (home-manager doesn't have this option):

```nix
xdg.configFile = {
  "zsh".source = lib.getExe pkgs.zsh;
  "shell" = {
    executable = true;
    text = ''
      exec ${config.xdg.configHome}/zsh "$@"
    '';
  };
};
```

```sh
❯ exa -l
# Output redacted
lrwxrwxrwx - geko 27 Nov 10:50 shell -> /nix/store/4i14b6xm10kapc6rmjpi94r4hxyfbqrl-home-manager-files/.config/shell
lrwxrwxrwx - geko 27 Nov 10:50 zsh -> /nix/store/4i14b6xm10kapc6rmjpi94r4hxyfbqrl-home-manager-files/.config/zsh
```

And this seems to work fine.

So I guess it's a combination of the filename home-manager chooses when creating links with `source`, and zsh's behavior when reading its argv.
